<?php

/*
|===============================================================================
|                                  WARNING
|
|                   /!\     DO NOT MODIFY THIS FILE     /!\
|-------------------------------------------------------------------------------
|
|   Do not modify the content of this file, it's generated by the command:
|   "php artisan models:generate" (package "axn/laravel-models-generator").
|
|   If you modify this file, when you call the command again,
|   your modifications will be overwritten.
|
|   If you want to add or modify a relation, do it in the model class or in
|   another trait.
|
*/

namespace App\Models\GeneratedRelations;

trait AtTownRelations
{

    /**
     * "has many" relation to `at_users` table
     * via `towid` field.
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function atUsersViaTowid()
    {
        return $this->hasMany(\App\Models\AtUser::class, 'towid');
    }

    /**
     * "belongs to" relation to `at_state` table
     * via `staid` field.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function stateRelation()
    {
        return $this->belongsTo(\App\Models\AtState::class, 'staid');
    }

}
